### ISSUE TITLE
Токены в БД хранятся в открытом виде

### ISSUE THREAD

**Issue by DavisDmitry** [civsocit/olgram#1]
Токены в БД хранятся в открытом виде, это небезопасно. Их нужно шифровать, ключ хранить в переменных окружения

**Comment by mihalin** [comment]
Не критично, если БД закрыта на том же VPS вместе с ботом. Но добавил шифрование. Спасибо за репорт )

**Comment by mihalin** [comment]
https://github.com/civsocit/olgram/commit/2e61640f5a10c438463ff29b89d9e8dfa79a2ee5
