### ISSUE TITLE
Возможность редактирования сообщений в диалоге бота

### ISSUE THREAD

**Issue by GordonFreeman-BY** [civsocit/olgram#10]
Хотелось бы наличие функции редактирования сообщений, в данный момент при редактировании сообщений на любой из сторон ничего не происходит(нет даже уведомления, что редактирование сообщений не поддерживается ботом).

- Когда пользователь бота редактирует сообщение, то в чате поддержки появляется новое сообщение(старое остаётся в неизменном виде).
- Когда сообщение редактируется в чате поддержки, то в чате с пользователем исходное сообщение меняет своё содержание(нового сообщения не отправляется, лишь редактируется текст уже существующего).

_P.S. Данный функционал реализуем с помощью Telegram API и уже используется в другом боте(неудобство использования бота, в котором это реализовано, на данный момент в отсутствии конструктора, который позволил бы запускать необходимое множество ботов быстро и просто в автоматическом режиме)._

**Comment by mihalin** [comment]
Проще. Во всех случаях отправляется новое сообщение. Done.
